version: '3.7'

services:
  go-app:
    container_name: go-app
    image: go-app:latest
    build: .
    environment:
      - DATABASE_URL="host=localhost port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - go-postgres
  go-postgres:
    container_name: go-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
